# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: features.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='features.proto',
  package='SynsetFeatures',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x66\x65\x61tures.proto\x12\x0eSynsetFeatures\"8\n\x0eRepresentation\x12\x14\n\x08\x66\x65\x61tures\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x10\n\x08image_id\x18\x06 \x01(\t\"W\n\x08\x46\x65\x61tures\x12\x37\n\x0frepresentations\x18\x07 \x03(\x0b\x32\x1e.SynsetFeatures.Representation\x12\x12\n\nmultiplier\x18\t \x01(\rb\x06proto3')
)




_REPRESENTATION = _descriptor.Descriptor(
  name='Representation',
  full_name='SynsetFeatures.Representation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='SynsetFeatures.Representation.features', index=0,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_id', full_name='SynsetFeatures.Representation.image_id', index=1,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=90,
)


_FEATURES = _descriptor.Descriptor(
  name='Features',
  full_name='SynsetFeatures.Features',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='representations', full_name='SynsetFeatures.Features.representations', index=0,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='SynsetFeatures.Features.multiplier', index=1,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=179,
)

_FEATURES.fields_by_name['representations'].message_type = _REPRESENTATION
DESCRIPTOR.message_types_by_name['Representation'] = _REPRESENTATION
DESCRIPTOR.message_types_by_name['Features'] = _FEATURES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Representation = _reflection.GeneratedProtocolMessageType('Representation', (_message.Message,), dict(
  DESCRIPTOR = _REPRESENTATION,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:SynsetFeatures.Representation)
  ))
_sym_db.RegisterMessage(Representation)

Features = _reflection.GeneratedProtocolMessageType('Features', (_message.Message,), dict(
  DESCRIPTOR = _FEATURES,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:SynsetFeatures.Features)
  ))
_sym_db.RegisterMessage(Features)


_REPRESENTATION.fields_by_name['features']._options = None
# @@protoc_insertion_point(module_scope)
