# Dataset options
dataset_path: "/home/mawanda/Documents/GoogleUniversalImageEmbedding/single_features"
train_dataset: "/home/mawanda/projects/GoogleUniversalImageEmbedding/dataset_info/train_synset_ids.txt"
val_dataset: "/home/mawanda/projects/GoogleUniversalImageEmbedding/dataset_info/val_synset_ids.txt"
multiplier: 10000

# Network options
in_features: 768
hidden_features: 1024
out_features: 64

# Training options
batch_size: 1536
epochs: 15000
lr: 1.e-3
weight_decay: 1.0e-6
optimizer: LARS
temperature: 0.2
momentum: 0.
device: cuda:0
val_steps: 20

# Checkpoint option
exp_path: "/home/mawanda/Documents/GoogleUniversalImageEmbedding/experiments/first_trial"
save_steps: 100
